@echo off
if /I "%~1"=="/silent" goto :RUN

:: First run (double-click): relaunch this same file completely hidden
:: in the background, then exit immediately. No window stays open and
:: nothing needs to be pressed.
powershell -NoProfile -WindowStyle Hidden -Command "Start-Process -WindowStyle Hidden -FilePath '%~f0' -ArgumentList '/silent'"
exit /b

:RUN
setlocal
:: ============================================================
::  Clipboard Auto-Replace  (single file, Windows, runs silently)
:: ============================================================
::  HOW TO USE
::   1. Edit the rules below, one per line, as FIND=REPLACE
::   2. Save this file, then double-click it. It runs silently in
::      the background - no window opens and there is nothing to
::      press.
::   3. Copy (Ctrl+C) anything containing FIND text, then Paste
::      (Ctrl+V) and you'll get the REPLACE version instead.
::   4. To stop it: open Task Manager, find "powershell.exe" /
::      "Windows PowerShell", and End Task.
::   5. To pick up rule changes: stop it (step 4), edit the rules,
::      save, then double-click this file again.
::
:: RULES START
:: 8888=TTTTT
:: 9999=TTTTT
:: 7777=TTTTT
:: 6666=TTTTT
:: 1111=TTTTT
:: 2222=TTTTT
:: 3333=TTTTT
:: 4444=TTTTT
:: 5555=TTTTT
:: RULES END
:: ============================================================

set "CAR_FILE=%~f0"
powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -EncodedCommand JABwAGEAdABoACAAPQAgACQAZQBuAHYAOgBDAEEAUgBfAEYASQBMAEUACgAkAGwAaQBuAGUAcwAgAD0AIABHAGUAdAAtAEMAbwBuAHQAZQBuAHQAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAcABhAHQAaAAgAC0ARQBuAGMAbwBkAGkAbgBnACAAVQBUAEYAOAAKACQAaQBuAFIAdQBsAGUAcwAgAD0AIAAkAGYAYQBsAHMAZQAKACQAbQBhAHAAIAA9ACAAWwBvAHIAZABlAHIAZQBkAF0AQAB7AH0ACgBmAG8AcgBlAGEAYwBoACAAKAAkAGwAIABpAG4AIAAkAGwAaQBuAGUAcwApACAAewAKACAAIAAgACAAJAB0ACAAPQAgACQAbAAuAFQAcgBpAG0AKAApAAoAIAAgACAAIABpAGYAIAAoACQAdAAgAC0AZQBxACAAJwA6ADoAIABSAFUATABFAFMAIABTAFQAQQBSAFQAJwApACAAewAgACQAaQBuAFIAdQBsAGUAcwAgAD0AIAAkAHQAcgB1AGUAOwAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgAGkAZgAgACgAJAB0ACAALQBlAHEAIAAnADoAOgAgAFIAVQBMAEUAUwAgAEUATgBEACcAKQAgAHsAIAAkAGkAbgBSAHUAbABlAHMAIAA9ACAAJABmAGEAbABzAGUAOwAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgAGkAZgAgACgAJABpAG4AUgB1AGwAZQBzACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJAB0AC4AUwB0AGEAcgB0AHMAVwBpAHQAaAAoACcAOgA6ACcAKQApACAAewAgACQAdAAgAD0AIAAkAHQALgBTAHUAYgBzAHQAcgBpAG4AZwAoADIAKQAuAFQAcgBpAG0AKAApACAAfQAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAdAAgAC0AZQBxACAAJwAnACkAIAB7ACAAYwBvAG4AdABpAG4AdQBlACAAfQAKACAAIAAgACAAIAAgACAAIAAkAGkAZAB4ACAAPQAgACQAdAAuAEkAbgBkAGUAeABPAGYAKAAnAD0AJwApAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABpAGQAeAAgAC0AbAB0ACAAMQApACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgACAAIAAgACAAJABmAGkAbgBkACAAPQAgACQAdAAuAFMAdQBiAHMAdAByAGkAbgBnACgAMAAsACAAJABpAGQAeAApAAoAIAAgACAAIAAgACAAIAAgACQAcgBlAHAAbAAgAD0AIAAkAHQALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAaQBkAHgAIAArACAAMQApAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABmAGkAbgBkACAALQBuAGUAIAAnACcAKQAgAHsAIAAkAG0AYQBwAFsAJABmAGkAbgBkAF0AIAA9ACAAJAByAGUAcABsACAAfQAKACAAIAAgACAAfQAKAH0ACgAKAEEAZABkAC0AVAB5AHAAZQAgAC0AQQBzAHMAZQBtAGIAbAB5AE4AYQBtAGUAIABTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMACgAKACQAbABhAHMAdABTAGUAZQBuACAAPQAgACQAbgB1AGwAbAAKACQAbABhAHMAdABTAGUAdAAgAD0AIAAkAG4AdQBsAGwACgAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIABTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAE0AaQBsAGwAaQBzAGUAYwBvAG4AZABzACAANQAwADAACgAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoAC0AbgBvAHQAIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEMAbABpAHAAYgBvAGEAcgBkAF0AOgA6AEMAbwBuAHQAYQBpAG4AcwBUAGUAeAB0ACgAKQApACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgACAAIAAgACAAJABjAHUAcgAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAEYAbwByAG0AcwAuAEMAbABpAHAAYgBvAGEAcgBkAF0AOgA6AEcAZQB0AFQAZQB4AHQAKAApAAoAIAAgACAAIAB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAIAAgACAAIABjAG8AbgB0AGkAbgB1AGUACgAgACAAIAAgAH0ACgAKACAAIAAgACAAaQBmACAAKABbAHMAdAByAGkAbgBnAF0AOgA6AEkAcwBOAHUAbABsAE8AcgBFAG0AcAB0AHkAKAAkAGMAdQByACkAKQAgAHsAIABjAG8AbgB0AGkAbgB1AGUAIAB9AAoAIAAgACAAIABpAGYAIAAoACQAYwB1AHIAIAAtAGUAcQAgACQAbABhAHMAdABTAGUAZQBuACAALQBvAHIAIAAkAGMAdQByACAALQBlAHEAIAAkAGwAYQBzAHQAUwBlAHQAKQAgAHsAIABjAG8AbgB0AGkAbgB1AGUAIAB9AAoAIAAgACAAIAAkAGwAYQBzAHQAUwBlAGUAbgAgAD0AIAAkAGMAdQByAAoACgAgACAAIAAgACQAbgBlAHcAIAA9ACAAJABjAHUAcgAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABrACAAaQBuACAAJABtAGEAcAAuAEsAZQB5AHMAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJABuAGUAdwAgAD0AIAAkAG4AZQB3AC4AUgBlAHAAbABhAGMAZQAoACQAawAsACAAJABtAGEAcABbACQAawBdACkACgAgACAAIAAgAH0ACgAKACAAIAAgACAAaQBmACAAKAAkAG4AZQB3ACAALQBuAGUAIAAkAGMAdQByACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4AQwBsAGkAcABiAG8AYQByAGQAXQA6ADoAUwBlAHQAVABlAHgAdAAoACQAbgBlAHcAKQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABhAHMAdABTAGUAdAAgAD0AIAAkAG4AZQB3AAoAIAAgACAAIAAgACAAIAAgAH0AIABjAGEAdABjAGgAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYwBvAG4AdABpAG4AdQBlAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgAH0ACgB9AAoA
exit /b
